version: "3.3"

networks:
    gocron:
        driver: bridge

services:
    gocron:
        container_name: gocron
        image: ouqg/gocron
        restart: always
        volumes:
            - ${CONF_DIR}:/app/conf
            - ${LOG_DIR}:/app/log
        ports:
            - "5920:5920"
        networks:
            - gocron
        command: ./gocron web
        tty: true
